name: Java CI (sans Maven)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compiler le code
        run: javac src/Main.java

      - name: Exécuter le programme
        run: java -cp src Main
